spring.application.name=xantrex-calculator

# PostgreSQL Datasource (values injected from environment — never hardcoded)
spring.datasource.url=jdbc:postgresql://dpg-d6n244nafjfc739es540-a.oregon-postgres.render.com:5432/cmpt_276_xantrex_database?sslmode=require
spring.datasource.username=cmpt_276_xantrex_database_user
spring.datasource.password=FMSTdUuNH5iA8Rx5LLXbBteuGnCjnyCN
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Spring Session JDBC
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true